---
name: E2E Tests
permissions:
  contents: read
  id-token: write

'on':
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        worker: [0, 1, 2]
    name: E2E Tests (Worker ${{ matrix.worker }})
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'
          cache: true

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Set GCP project environment variable
        run: echo "GCP_PROJECT=${{ secrets.GCP_PROJECT_ID }}" >> $GITHUB_ENV

      - name: Run E2E tests
        run: |
          chmod +x ./run_e2e_tests_subset.sh
          PARALLEL_TESTS=10 WORKER_INDEX=${{ matrix.worker }} TOTAL_WORKERS=3 ./run_e2e_tests_subset.sh
        timeout-minutes: 50
        env:
          WORKER_INDEX: ${{ matrix.worker }}
          TOTAL_WORKERS: 3

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-results-worker-${{ matrix.worker }}
          path: |
            *.log
            e2e_tests/*.log
          retention-days: 7

  e2e-tests-summary:
    name: E2E Tests Summary
    runs-on: ubuntu-latest
    needs: e2e-tests
    if: always()
    steps:
      - name: Check test results
        run: |
          if [ "${{ needs.e2e-tests.result }}" == "failure" ]; then
            echo "One or more test workers failed"
            exit 1
          elif [ "${{ needs.e2e-tests.result }}" == "cancelled" ]; then
            echo "Test run was cancelled"
            exit 1
          else
            echo "All test workers completed successfully"
          fi
