---
name: Nightly E2E Tests
permissions:
  contents: read
  id-token: write
  issues: write

'on':
  schedule:
    # Run nightly at 2 AM UTC (adjust as needed)
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  nightly-e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'
          cache: true

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Set GCP project environment variable
        run: echo "GCP_PROJECT=${{ secrets.GCP_PROJECT_ID }}" >> $GITHUB_ENV

      - name: Run E2E tests
        run: |
          chmod +x ./run_tests.sh
          # Use default parallelism (4) for nightly runs since we have more time
          # Capture test output to log file for issue creation
          PARALLEL_TESTS=1 ./run_tests.sh 2>&1 | tee nightly-test-output.log
        timeout-minutes: 50

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: nightly-e2e-test-results-${{ github.run_number }}
          path: |
            *.log
            e2e_tests/*.log
            nightly-test-output.log
          retention-days: 30

      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const { owner, repo } = context.repo;
            const runUrl = `https://github.com/${owner}/${repo}/actions/runs/${context.runId}`;
            
            // Read test output log file
            let testOutput = '';
            let failureSummary = '';
            try {
              const logContent = fs.readFileSync('nightly-test-output.log', 'utf8');
              
              // Extract failure information from the log
              const lines = logContent.split('\n');
              const failureLines = [];
              let failedTests = [];
              let seenFailures = new Set();
              
              for (let i = 0; i < lines.length; i++) {
                const line = lines[i];
                
                // Look for test failure patterns
                if (line.includes('--- FAIL:')) {
                  const testMatch = line.match(/--- FAIL: (\w+)/);
                  if (testMatch && !seenFailures.has(testMatch[1])) {
                    failedTests.push(testMatch[1]);
                    seenFailures.add(testMatch[1]);
                    failureLines.push(line);
                  }
                } else if (line.trim().startsWith('dlr_test.go:') || 
                          line.trim().startsWith('move_test.go:') ||
                          line.trim().startsWith('e2e_tests/') ||
                          line.includes('Error:') || 
                          line.includes('Failed to') ||
                          line.includes('rpc error:') ||
                          line.includes('panic:') ||
                          line.includes('exit status')) {
                  failureLines.push(line);
                }
              }
              
              // Limit the output to avoid GitHub API limits (GitHub issues have ~65k limit)
              const maxLength = 3000;
              if (failureLines.length > 0) {
                testOutput = failureLines.join('\n');
                if (testOutput.length > maxLength) {
                  testOutput = '...\n' + testOutput.slice(testOutput.length - maxLength + 4);
                }
              }
              
              // Create failure summary
              if (failedTests.length > 0) {
                failureSummary = `**Failed Tests:** ${failedTests.join(', ')}\n\n`;
              }
              
            } catch (error) {
              console.log('Could not read test output log:', error.message);
              testOutput = 'Test output log not available. Check the workflow artifacts for detailed logs.';
            }
            
            // Create an issue if nightly tests fail
            const title = `Nightly E2E Tests Failed - ${new Date().toISOString().split('T')[0]}`;
            const body = `The nightly E2E tests failed on ${new Date().toISOString().split('T')[0]}.

            **Run URL:** ${runUrl}
            
            **Run ID:** ${context.runId}
            
            ${failureSummary}**Test Failure Output:**
            \`\`\`
            ${testOutput}
            \`\`\`
            
            **Next Steps:**
            1. Check the complete logs in the workflow artifacts: [Test Results](${runUrl}#artifacts)
            2. Review the failing tests and error messages above
            3. Run the failing tests locally to reproduce the issue
            4. Fix the underlying issue and verify with local test runs
            
            This issue was automatically created by the nightly E2E test workflow.`;
            
            // Check if there's already an open issue for today's date
            const issues = await github.rest.issues.listForRepo({
              owner,
              repo,
              state: 'open',
              labels: 'nightly-test-failure'
            });
            
            const today = new Date().toISOString().split('T')[0];
            const existingIssue = issues.data.find(issue => 
              issue.title.includes(today)
            );
            
            if (!existingIssue) {
              await github.rest.issues.create({
                owner,
                repo,
                title,
                body,
                labels: ['nightly-test-failure', 'bug']
              });
            }