---
name: Nightly E2E Tests
permissions:
  contents: read
  id-token: write
  issues: write

'on':
  schedule:
    # Run nightly at 2 AM UTC (adjust as needed)
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  nightly-e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'
          cache: true

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Set GCP project environment variable
        run: echo "GCP_PROJECT=${{ secrets.GCP_PROJECT_ID }}" >> $GITHUB_ENV

      - name: Run E2E tests
        run: |
          chmod +x ./run_tests.sh
          # Use default parallelism (4) for nightly runs since we have more time
          PARALLEL_TESTS=1 ./run_tests.sh
        timeout-minutes: 50

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: nightly-e2e-test-results-${{ github.run_number }}
          path: |
            *.log
            e2e_tests/*.log
          retention-days: 30

      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const runUrl = `https://github.com/${owner}/${repo}/actions/runs/${context.runId}`;
            
            // Create an issue if nightly tests fail
            const title = `Nightly E2E Tests Failed - ${new Date().toISOString().split('T')[0]}`;
            const body = `The nightly E2E tests failed on ${new Date().toISOString().split('T')[0]}.

            **Run URL:** ${runUrl}
            
            **Run ID:** ${context.runId}
            
            Please investigate the failure and fix any issues found.
            
            This issue was automatically created by the nightly E2E test workflow.`;
            
            // Check if there's already an open issue for today's date
            const issues = await github.rest.issues.listForRepo({
              owner,
              repo,
              state: 'open',
              labels: 'nightly-test-failure'
            });
            
            const today = new Date().toISOString().split('T')[0];
            const existingIssue = issues.data.find(issue => 
              issue.title.includes(today)
            );
            
            if (!existingIssue) {
              await github.rest.issues.create({
                owner,
                repo,
                title,
                body,
                labels: ['nightly-test-failure', 'bug']
              });
            }